### ISSUE TITLE
logo and favicon are overwritten

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#10]
The migration overwrites the /img/logo.jpg and /img/favicon.ico files. This should not happen.

**Comment by Traumflug** [comment]
It's not a bug, it's a feature! :-)

Honestly, as thirty bees supports more favicon and mobile desktop icon sizes than PS, a merchant has to upload a new/larger favicon anyways, to get these additional sizes computed. As such the overwritten traditional favicon is probably a good reminder to not forget this.

Nevertheless, thanks for reporting!
