### ISSUE TITLE
Products have initially no image

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#11]
After the migration the products have no image in the category list (grid or list view makes no difference). So it looks like this:
![thirty10](https://user-images.githubusercontent.com/13930107/30813328-7190de0e-a20d-11e7-9b06-0e8cdc6aad82.jpg)

I tried regenerating images but that makes no difference.

After you visit the product page however, the product image is displayed - both on the product and the category page.
![thirty11](https://user-images.githubusercontent.com/13930107/30813402-a27c6a6a-a20d-11e7-8268-23a7614655ff.jpg)

**Comment by firstred** [comment]
Does you XAMPP read the `.htaccess` (`AllowOverrides on` in vconf)?

**Comment by musicpanda** [comment]
I don't think these symptoms are the  symptoms of an AllowOverride problem. 

When I have a fresh installation of TB in the same setting this problem does not happen. 

Also I noticed that when I reload the category page a few hours later the image has disappeared again. It looks like there is something funny going on with caching.

**Comment by musicpanda** [comment]
I am not 100% sure of that disappearing - it may have been another of my testshops.

However, I did notice that when I add an image to an existing product and make it default it is initially hidden too.

**Comment by musicpanda** [comment]
Yes, it disappeared again this morning.

But now all pictures have suddenly appeared. I have no idea why. So I close this issue as I cannot reproduce it anymore (and I don't feel like wasting more time on it). 

Let's just hope it doesn't turn up again later on...
