### ISSUE TITLE
Movemodules issue

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#19]
My upgrade hangs this time on "moving aside incompatible modules". It is hard to say from the error message what is going wrong.

One possibility is that this concerns a module that is still in the database but no longer on the disk. 

Jqxhr messages are a horror that only tell initiates that something unspecified went wrong with an ajax call. In this case at least the name of the module should have been mentioned. It might be considered to provide the guilty ajax call with all its arguments.

note 1: in this case debug mode was off.
note 2: I tried several times but always with the same result. Finally I got out of the situation by upgrading the shop to Prestashop 1.6.1.23 first. After that psonesixmigrator worked ok.

![jqxhr](https://user-images.githubusercontent.com/13930107/54892346-8e97c600-4eb1-11e9-8439-20f29f3ee271.jpg)

**Comment by khassad** [comment]
Hi, I stumbled on the very same error at the same step with the latest psonesixmigrator module  v2.0.1, Prestashop 1.6.23 so the latest 1.6.x line release.
This is a blocking issue that prevents the upgrade.
In my case I found the culprit by activating the PHP error log. There was a stack trace of the fatal error in module blockmyaccountfooter.
" PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::createData()"
I deinstalled the blockmyaccountfooter module and the migration went smoothly.

Hopes this helps and maybe you could improve the psonesixmigrator to handle this correctly.

**Comment by Traumflug** [comment]
Probably can't help much with the error display problem. These 500 errors usually mean a PHP problem, so one should find something in _log/_ in the shop root folder.

**Comment by Traumflug** [comment]
To remove the showstopper, I wrapped module uninstallation in `try ... catch`, hopefully replacing this Exception with an error message and accordingly, these type 500 errors going away. See 8be7f2ad09c957637d2e819a805bfb1130bc0514.

A module release will follow before too long.

**Comment by Traumflug** [comment]
The new module release happened: https://github.com/thirtybees/psonesixmigrator/releases/tag/2.1.0

I hope this removes these nasty showstoppers. If it doesn't, please don't hesitate to re-open this issue or open another one.

**Comment by khassad** [comment]
Thanks !

**Comment by bullmade** [comment]
Unfortunately, the issue is still there.
Tried to migrate a PS 1.6.1.11 to tb 1.0.8

Got error:
[Ajax / Server Error for action deleteModules] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: " "
