### ISSUE TITLE
DashProducts xml

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#20]
After the migration the Prestashop modules are replaced by their Thirty Bees equivalents. In the case of Dash Products it looks like that doesn't happen completely: the config.xml afterwards still says that the author is Prestashop while in the dashproducts.php file the author is thirtybees.

I know this is a small thing. But if this happens to one file it may happen to other too...

**Comment by Traumflug** [comment]
Thanks for the report. That's a bit surprising, because updating a module should delete it's entire folder, then unpack the new version. This should also delete `config.xml`, which gets re-created automatically.

**Comment by Traumflug** [comment]
This isn't a problem of the migration module, but of thirty bees module update code. Tracked in https://github.com/thirtybees/thirtybees/issues/1025
