### ISSUE TITLE
Adds menu thumbnails to category id 3 after migration

### ISSUE THREAD

**Issue by bullmade** [thirtybees/psonesixmigrator#21]
After the migration is complete, two images is added to the category ID 3 as menu thumbnails.
![image](https://user-images.githubusercontent.com/16975198/56471411-6e2c3e80-6452-11e9-9738-ca376a7e2258.png)

**Comment by Traumflug** [comment]
Thanks for the report. I removed these two images from the list of files to add on migration, previously existing ones, if existing, are kept now.

This should be in effect immediately, without a change to the module. If not, please don't hesitate to re-open this issue.
