### ISSUE TITLE
Module installation

### ISSUE THREAD

**Issue by Ezyweb-uk** [thirtybees/psonesixmigrator#22]
The Readme says "The module installs like a normal PrestaShop module" but it looks like the files have to first be built into a package. Is there a pre-compiled version of this module available please?

**Comment by getdatakick** [comment]
Yes, it can be found in Releases tab: https://github.com/thirtybees/psonesixmigrator/releases

https://github.com/thirtybees/psonesixmigrator/releases/download/2.0.1/psonesixmigrator-v2.0.1.zip
