### ISSUE TITLE
zip->extractTo(): unable to use /home/customer/www/XXX/public_html/admin123/psonesixmigrator/latest as extract destination.

### ISSUE THREAD

**Issue by mrpoe1** [thirtybees/psonesixmigrator#26]
Hi,
I'm trying to migrate for the first time and I faced an error:
The module download the package, then seems to try to extract on public_html folder and fails on PS 1.6.1.15

Analyzing the situation...Shop deactivated. Now downloading... (this can take a while)
Download complete. Now extracting...
Unable to extract /home/customer/www/XXX/public_html/admin123/psonesixmigrator/download/thirtybees-v1.0.8.zip and/or /home/customer/www/XXX/public_html/admin123/psonesixmigrator/download/thirtybees-extra-v1.0.8.zip into /home/customer/www/XXX/public_html/admin123/psonesixmigrator/latest folder...
Errors
zip->extractTo(): unable to use /home/customer/www/XXX/public_html/admin123/psonesixmigrator/latest as extract destination.
Archives will come from https://github.com/thirtybees/thirtybees/releases/download/1.0.8/thirtybees-v1.0.8.zip and https://api.thirtybees.com/migration/packs/thirtybees-extra-v1.0.8.zip
md5 hashes for core and extra should be resp. 805bf1b9e8ee6abf17e5e32f0b433a9f and 5ff8a5beb7c24d96643c0006c68e0fdf
Directory tests complete.
Downloading from https://github.com/thirtybees/thirtybees/releases/download/1.0.8/thirtybees-v1.0.8.zip and https://api.thirtybees.com/migration/packs/thirtybees-extra-v1.0.8.zip
Files will be saved to /home/customer/www/XXX/public_html/admin123/psonesixmigrator/download/thirtybees-v1.0.8.zip and /home/customer/www/XXX/public_html/admin123/psonesixmigrator/download/thirtybees-extra-v1.0.8.zip
Downloads took 1 seconds.
Download complete.
"/latest" directory has been emptied
zip->extractTo(): unable to use /home/customer/www/XXX/public_html/admin123/psonesixmigrator/latest as extract destination.

Thank you

**Comment by getdatakick** [comment]
This looks like file system permission issues. Please check write permissions

**Comment by mrpoe1** [comment]
> This looks like file system permission issues. Please check write permissions

I already check: all folders are 774 and files 664.
Also I run a script to force all permission with hosting.
Even if it gives error,  "latest" folder was created and 90% of files was unzipped in it.
I also deleted "latest" folder, and run again the the migration.
The results was the same. 
I have no disk quota limits (250gb free), and the script wasn't killed by any PHP limit.

Anyway i give up, thanks anyway
