### ISSUE TITLE
Going to migrate to thirty bees version: Nothing available

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#28]
I finally "solved" my not writable problem by ignoring it. 

What remains is a small "feature" of psonesixmigrator. It says that _Going to migrate to thirty bees version: Nothing available_
And indeed, when I press the "migrate to Thirty Bees" button nothing happens.

![migrate4](https://user-images.githubusercontent.com/13930107/172684442-b8e6b2a0-8006-463d-a0f9-c869dce2966b.jpg)

**Comment by getdatakick** [comment]
Looks like the request to api server failed. This could be caused by issue #25. Please try to download https://github.com/thirtybees/thirtybees/blob/main/tools/cacert.pem and use it to replace cacert.pem file that comes with the module.

If that does not help, then the issue will be elsewhere:

- php server misconfiguration -- outgoing requests are blocked by php settings or security module
- firewall installed on your server

**Comment by getdatakick** [comment]
I've just release version 2.1.1 with the updated cacert.pem file

**Comment by deweblooper** [comment]
I confirm, using psonesixmigrator 2.1.1 on clean new Prestashop 1.6.1.24 works fine, even admin password is correctly recoded.
thank you [getdatakick](https://github.com/getdatakick)

**Comment by musicpanda** [comment]
I had a day off so I just tested. It didn't work for me. It says now that it is going to migrate to 1.08. But pressing the button still has no effect.

When I look at the Ajax call I see a notice about _PS_CREATION_DATE_ already being defined.

![migrate5](https://user-images.githubusercontent.com/13930107/172920213-d80259a4-f646-45ec-b07c-19dca03e4132.jpg)

**Comment by musicpanda** [comment]
There was indeed a double creation date in settings.inc.php. I fixed it and after that things worked.

BTW. I found also another error message about the creation date that somehow I ad missed previously:
![migrate6](https://user-images.githubusercontent.com/13930107/172922917-bfe0f1f1-f561-443a-909d-e53c4e5df9e6.jpg)

**Comment by getdatakick** [comment]
The original issue seems to be fixed. I have filed two follow up issues to track your other problems
