### ISSUE TITLE
Name Display Problem in Modullist

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/psonesixmigrator#3]
![name-bug](https://cloud.githubusercontent.com/assets/15154932/25617252/a6e923ca-2f41-11e7-80b9-81fa3f85eeb3.jpg)

Not a big issue, but not so nice...

**Comment by Dh42** [comment]
This was fixed at some point, I think @getdatakick  might have fixed it, but I just checked, http://i.imgur.com/5iQrHMm.png
