### ISSUE TITLE
Disabling PS modules leads to confusion

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/psonesixmigrator#7]
During the migration TB disables all non-TB modules. This is in line with Prestashop disabling all non-Prestashop modules during an upgrade.

However, all non-TB modules means also all Prestashop modules. And as the upgrade does not replace modules with their ThirtyBees equivalent this means that almost all modules are replaced. The result is a completely dysfunctional website that easily leads to the conclusion that the upgrade has gone wrong. Even such basics as the footer are missing.

So my proposal is either to replace some PS modules with their TB equivalent or to treat some PS modules as TB modules.

**Comment by musicpanda** [comment]
The need for upgrades applies extra for the Blockrss module that produces a warning in the backoffice:
![thirty8](https://user-images.githubusercontent.com/13930107/30786190-98788a44-a172-11e7-9905-16fa2221aaac.jpg)

**Comment by firstred** [comment]
Even the latest version of the `blockrss` module? We've removed the previous `blockrss` module as it uses a library that doesn't support PHP 7.0+, so it has to be removed asap.

**Comment by firstred** [comment]
Replaced*

**Comment by firstred** [comment]
> So my proposal is either to replace some PS modules with their TB equivalent or to treat some PS modules as TB modules.

Good catch, thanks! Hadn't thought of that actually. The first idea was to disable all non-tb stuff, but that indeed includes PS modules. Since most of those modules have tb equivalents it is probably best to immediately swap them with the thirty bees ones, but that's got to be tested first

**Comment by musicpanda** [comment]
I assume it was still the Prestashop RSS module.

**Comment by Traumflug** [comment]
Not sure *when* it was fixed, but native modules get recognized by name for quite a while now: https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/module/Module.php#L1210-L1215 (core code, which is synchronized with module code). This should remove the distinction by module author.

In case the issue persists, please don't hesitate to open another issue.
